#!/bin/bash

S3='https://s3-us-west-2.amazonaws.com/percptv/oneDay'
cd /data
if [ ! -d .dlcvtf_old ]; then
	mkdir .dlcvtf_old
fi
x=`ls | grep -F .py`
if [ ! -z "$x" ]; then
	mv -f *.py .dlcvtf_old
fi
x=`ls | grep -F .ipynb`
if [ ! -z "$x" ]; then
	mv -f *.ipynb .dlcvtf_old
fi
curl -O ${S3}/00_test_install.ipynb
curl -O ${S3}/01_linear_regression.ipynb
curl -O ${S3}/02_logistic_regression_mnist.ipynb
curl -O ${S3}/03_deep_neural_network_mnist.ipynb
curl -O ${S3}/04_MNIST_Slim_CNN.ipynb
curl -O ${S3}/05_MNIST_Slim_CNN_visualize.ipynb

cp -f /usr/local/dlcvtf/oneDay/data/* /tmp
source /opt/DL/tensorflow/bin/tensorflow-activate
